[project]
name = "zer-openapi-specs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "pytest-html>=4.1.1",
    "requests>=2.32.4",
    "schemathesis>=4.0.6",
]
